// Generated by CoffeeScript 1.3.3

/*
bsd license
*/


(function() {
  var strFormats,
    __slice = [].slice;

  String.prototype.repeat = function(count) {
    var i;
    return ''.concat((function() {
      var _i, _results;
      _results = [];
      for (i = _i = 0; 0 <= count ? _i < count : _i > count; i = 0 <= count ? ++_i : --_i) {
        _results.push(this);
      }
      return _results;
    }).call(this));
  };

  String.prototype.lpad = function(length, chr) {
    if (chr == null) {
      chr = ' ';
    }
    return chr.repeat(length - this.length) + str;
  };

  String.prototype.rpad = function(length, chr) {
    if (chr == null) {
      chr = ' ';
    }
    return str + chr.repeat(length - this.length);
  };

  parse;


  strFormats = {
    d: function(val, fmt) {
      if (fmt == null) {
        fmt = ' ';
      }
    },
    x: function() {},
    s: function() {}
  };

  /*
  
  %d, 3 -> 3
  %02d, 3 -> 03
  */


  String.prototype.format = function() {
    var args;
    args = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
    return this.replace(/%((?:\d*?d))/gi, function(_, format) {
      var f, farg;
      f = format.slice(-1);
      farg = format.slice(0, -1);
      return strFormats[f].call(null, args.pop, farg);
    });
  };

  (function() {
    var formats;
    formats = {
      y: function() {
        return this.getFullYear();
      },
      M: function() {},
      '%': function() {
        return '%';
      }
    };
    return this.dateFormat = function(fmt, date) {
      if (date == null) {
        date = new Date();
      }
      return fmt.replace(/%([yMd%]|)/g, function(_, format) {
        return formats[format].call(date);
      });
    };
  })();

}).call(this);
